### ISSUE TITLE
mkdocs serve error

### ISSUE THREAD

**Issue by will-wright-eng** [waynerv/cookiecutter-pypackage#9]
* Date you used Cookiecutter PyPackage: 2022-07-14
* Cookiecutter version used, if any:
* Python version, if any:
* Operating System: macos

### Description

Followed Tutorial

### What I Did

```bash
poetry run mkdocs serve
```

> FileNotFoundError: [Errno 2] No such file or directory:

**The fix** is to change the watched directory within `mkdocs.yml` from project_slug to pkg_name:
https://github.com/waynerv/cookiecutter-pypackage/blob/f94e6534590f49b079f91aef31666faa217a53e6/%7B%7Bcookiecutter.project_slug%7D%7D/mkdocs.yml#L54

```
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - {{ cookiecutter.pkg_name }}
```

**Comment by sylvanding** [comment]
It's recommended to use the following poetry dependencies related to mkdocs:

```toml
[tool.poetry.dependencies]

mkdocs = { version = "<=1.2.1", optional = true }
mkdocs-include-markdown-plugin = { version = "<=1.0.0", optional = true }
mkdocs-material = { version = "<=6.1.7", optional = true }
mkdocstrings = { version = "<=0.15.2", optional = true }
mkdocs-material-extensions = { version = "<=1.0.1", optional = true }
mkdocs-autorefs = { version = "<=0.2.1", optional = true }

# --- Adjust dependencies, also see setup.cfg [testenv:build] deps ---
# solve problem: Package docutils (0.21.post1) not found.
docutils = { version = "<=0.18.0", optional = true }
# solve problem: Cannot import name 'contextfunction' from 'jinja2'.
jinja2 = { version = "<=2.11.3", optional = true }
# solve problem: Cannot import name 'soft_unicode' from 'markupsafe'.
markupsafe = { version = "<=2.0.1", optional = true }
# solve problem: InlineHtmlFormatter.wrap() missing 1 required positional argument: 'outfile'.
pygments = { version = "<=2.9.0", optional = true }
# solve problem: pymdownx does not work with mkdocs
pymdown-extensions = { version = "<=7.1", optional = true }
# --- End of Adjust Dependencies ---
```
